# Generated by Django 5.2.3 on 2025-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('archived', 'Archived')], default='pendiente', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
